logging:
  level:
    root: INFO
schedule:
  enabled: "true"
  delay: 10000
client-services:
  serviceList:
    - serviceName: "attachment-svc"
      port: ""
      path: "https://1mrb515ysf.api.quickmocker.com"
    - serviceName: "attachment-svc2"
      port: ""
      path: "https://1mrb515ysf.api.quickmocker.com/actuator/ok"
failureThreshold: "3"

geo-healthcheck:
  serviceName: "geo-endpoint-host"
  port: "80"
