logging:
  level:
    root: INFO
schedule:
  enabled: true
  delay: 2000
client-services:
  service-list:
    - endpoint: http://yandex.ru/abc
      delay: 2000
      failure-threshold: 3
    - endpoint: http://google.ru/
      delay: 3000
      failure-threshold: 3

geo-healthcheck-list:
  - endpoint: http://yandex.ru/abc
    failure-threshold: 3
