logging:
  level:
    root: INFO
schedule:
  enabled: "true"
  delay: 2000
client-services:
  service-list:
    - service-name: "yandex.ru"
      port: ""
      path: ""
    - service-name: "yandex.ru/abcd"
      port: ""
      path: ""
failure-threshold: "3"

geo-healthcheck:
  service-name: "google.ru"
  port: ""
