logging:
  level:
    root: INFO
schedule:
  enabled: "true"
  delay: 1000
client-services:
  serviceList:
    - serviceName: "https://yandex.ru"
      port: ""
      path: ""
    - serviceName: "https://yandex.ru/abcd"
      port: ""
      path: ""
failureThreshold: "3"

geo-healthcheck:
  serviceName: "geo-endpoint-host"
  port: "80"
